services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  perform_ocr:
    build:
      context: .
      dockerfile: PerformOCR/Dockerfile
    deploy:
      replicas: 3
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  filter_pii:
    build:
      context: .
      dockerfile: FilterPII/Dockerfile
    deploy:
      replicas: 3
    depends_on:
      - rabbitmq
      - redis
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
