version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  perform_ocr:
    build: ./PerformOCR
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  filter_pii:
    build: ./FilterPII
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
